# Generated by Django 4.1.3 on 2022-11-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_remove_letter_receiver_remove_letter_send_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
