# Generated by Django 4.1.3 on 2022-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letter_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
